name: Graybox Repo Sync POC

on:
  push:
    branches:
      - stage
      - main
  workflow_dispatch:
    inputs:
      syncBranch:
        description: 'Branch to sync'
        required: true
        default: 'stage'
        type: choice
        options:
          - 'stage'
          - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.FG_SYNC_APP_ID }}
          private-key: ${{ secrets.FG_SYNC_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "repo-b"

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ inputs.syncBranch || github.ref_name }}

      - name: Clone Graybox Repository and Checkout Stage Branch
        run: |
          git clone https://github.com/sukamat/repo-b.git ../repo-b
          cd ../repo-b
          git checkout $GB_SYNC_BRANCH
          echo "repo-b branch"
          git branch
          cd ../repo-a
          echo "repo-a branch"
          git branch
        env:
          GB_SYNC_BRANCH: ${{ inputs.syncBranch || github.ref_name }}

      - name: Overwrite graybox repo files with latest from source repo
        run: |
          rsync -av --exclude='fstab.yaml' --exclude='.github' --exclude='.git' --exclude='.idea' --exclude='.husky' --exclude='.vscode' --exclude='tools/sidekick/config.json' ./ ../repo-b/

      - name: Commit and Push Changes to repo-b Repository
        run: |
          cd ../repo-b
          echo "repo-b branch"
          git branch
          git config user.email "$FG_SYNC_BOT_EMAIL"
          git config user.name "graybox-repo-sync[bot]"
          git status          
          git remote set-url origin https://oauth2:$GITHUB_TOKEN@github.com/sukamat/repo-b.git
          git remote -v
          git add .
          git commit -m "Syncing repo-a to repo-b"
          git push origin $GB_SYNC_BRANCH --force
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          FG_SYNC_BOT_EMAIL: ${{ secrets.FG_SYNC_BOT_EMAIL }}
          GB_SYNC_BRANCH: ${{ inputs.syncBranch || github.ref_name }}
